# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_by',
            field=models.ManyToManyField(blank=True, related_name='likes_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
