# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_likes_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_by',
        ),
    ]
