# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
